-- ==========================================
-- SCRIPT DE MIGRACIÓN Y BASE DE DATOS LABOS
-- Ejecutar este script en el SQL Editor de Supabase
-- ==========================================

-- 1. Agregar columna de teléfono en la tabla 'usuarios'
ALTER TABLE usuarios 
ADD COLUMN IF NOT EXISTS telefono TEXT;

-- 2. Crear la tabla de 'gastos'
CREATE TABLE IF NOT EXISTS gastos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha DATE NOT NULL DEFAULT CURRENT_DATE,
    concepto TEXT NOT NULL,
    monto DECIMAL(12, 2) NOT NULL,
    tipo_producto TEXT, -- Categoría (ej: Materiales, Servicios, Renta, etc.)
    proveedor TEXT,
    comprobante_url TEXT,
    creado_por TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    laboratorio_id TEXT
);

-- Habilitar Row Level Security (RLS) en 'gastos' si es necesario
ALTER TABLE gastos ENABLE ROW LEVEL SECURITY;

-- Crear políticas básicas en 'gastos' para usuarios autenticados
CREATE POLICY "Permitir todo a usuarios autenticados en gastos" 
ON gastos FOR ALL 
TO authenticated 
USING (true) 
WITH CHECK (true);

-- 3. Crear la tabla de 'gastos_detalle'
CREATE TABLE IF NOT EXISTS gastos_detalle (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gasto_id BIGINT REFERENCES gastos(id) ON DELETE CASCADE,
    descripcion TEXT NOT NULL,
    cantidad DECIMAL(10, 2) NOT NULL DEFAULT 1.0,
    precio_unitario DECIMAL(12, 2) NOT NULL,
    subtotal DECIMAL(12, 2) NOT NULL
);

-- Habilitar RLS en 'gastos_detalle'
ALTER TABLE gastos_detalle ENABLE ROW LEVEL SECURITY;

-- Crear políticas básicas en 'gastos_detalle' para usuarios autenticados
CREATE POLICY "Permitir todo a usuarios autenticados en gastos_detalle" 
ON gastos_detalle FOR ALL 
TO authenticated 
USING (true) 
WITH CHECK (true);

-- 4. Soporte para nomenclaturas dentales (FDI / ADA)
CREATE TABLE IF NOT EXISTS public.notacion_dental (
  fdi TEXT PRIMARY KEY,
  ada TEXT NOT NULL
);

INSERT INTO public.notacion_dental (fdi, ada) VALUES
('18','1'),('17','2'),('16','3'),('15','4'),('14','5'),('13','6'),('12','7'),('11','8'),
('21','9'),('22','10'),('23','11'),('24','12'),('25','13'),('26','14'),('27','15'),('28','16'),
('38','17'),('37','18'),('36','19'),('35','20'),('34','21'),('33','22'),('32','23'),('31','24'),
('41','25'),('42','26'),('43','27'),('44','28'),('45','29'),('46','30'),('47','31'),('48','32')
ON CONFLICT (fdi) DO NOTHING;

ALTER TABLE public.clientes 
ADD COLUMN IF NOT EXISTS notacion_dental TEXT DEFAULT 'FDI' 
CHECK (notacion_dental IN ('FDI', 'ADA'));
