-- ==========================================
-- SCRIPT DE MIGRACIÓN Y BASE DE DATOS LABOS
-- Ejecutar este script en el SQL Editor de Supabase
-- ==========================================

-- 1. Agregar columna de teléfono en la tabla 'usuarios'
ALTER TABLE usuarios 
ADD COLUMN IF NOT EXISTS telefono TEXT;

-- 2. Crear la tabla de 'gastos'
CREATE TABLE IF NOT EXISTS gastos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha DATE NOT NULL DEFAULT CURRENT_DATE,
    concepto TEXT NOT NULL,
    monto DECIMAL(12, 2) NOT NULL,
    tipo_producto TEXT, -- Categoría (ej: Materiales, Servicios, Renta, etc.)
    proveedor TEXT,
    comprobante_url TEXT,
    creado_por TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    laboratorio_id TEXT
);

-- Habilitar Row Level Security (RLS) en 'gastos' si es necesario
ALTER TABLE gastos ENABLE ROW LEVEL SECURITY;

-- Crear políticas básicas en 'gastos' para usuarios autenticados
CREATE POLICY "Permitir todo a usuarios autenticados en gastos" 
ON gastos FOR ALL 
TO authenticated 
USING (true) 
WITH CHECK (true);

-- 3. Crear la tabla de 'gastos_detalle'
CREATE TABLE IF NOT EXISTS gastos_detalle (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gasto_id BIGINT REFERENCES gastos(id) ON DELETE CASCADE,
    descripcion TEXT NOT NULL,
    cantidad DECIMAL(10, 2) NOT NULL DEFAULT 1.0,
    precio_unitario DECIMAL(12, 2) NOT NULL,
    subtotal DECIMAL(12, 2) NOT NULL
);

-- Habilitar RLS en 'gastos_detalle'
ALTER TABLE gastos_detalle ENABLE ROW LEVEL SECURITY;

-- Crear políticas básicas en 'gastos_detalle' para usuarios autenticados
CREATE POLICY "Permitir todo a usuarios autenticados en gastos_detalle" 
ON gastos_detalle FOR ALL 
TO authenticated 
USING (true) 
WITH CHECK (true);
